-- Migration: add extra columns for clients and drivers
USE hortifrut;

ALTER TABLE clientes
  ADD COLUMN IF NOT EXISTS cpf_cnpj VARCHAR(50) NULL AFTER nome,
  ADD COLUMN IF NOT EXISTS email VARCHAR(150) NULL AFTER telefone,
  ADD COLUMN IF NOT EXISTS uf VARCHAR(2) NULL AFTER email,
  ADD COLUMN IF NOT EXISTS status TINYINT(1) NOT NULL DEFAULT 1 AFTER uf;

ALTER TABLE motoristas
  ADD COLUMN IF NOT EXISTS placa VARCHAR(50) NULL AFTER nome,
  ADD COLUMN IF NOT EXISTS veiculo VARCHAR(150) NULL AFTER placa,
  ADD COLUMN IF NOT EXISTS uf VARCHAR(2) NULL AFTER veiculo,
  ADD COLUMN IF NOT EXISTS status TINYINT(1) NOT NULL DEFAULT 1 AFTER uf;
