-- Migration: add address fields for clients and suppliers
USE hortifrut;

ALTER TABLE clientes
  ADD COLUMN IF NOT EXISTS endereco VARCHAR(255) NULL AFTER nome,
  ADD COLUMN IF NOT EXISTS numero VARCHAR(20) NULL AFTER endereco,
  ADD COLUMN IF NOT EXISTS complemento VARCHAR(100) NULL AFTER numero,
  ADD COLUMN IF NOT EXISTS bairro VARCHAR(100) NULL AFTER complemento,
  ADD COLUMN IF NOT EXISTS cep VARCHAR(20) NULL AFTER bairro;

ALTER TABLE fornecedores
  ADD COLUMN IF NOT EXISTS endereco VARCHAR(255) NULL AFTER razao_social,
  ADD COLUMN IF NOT EXISTS numero VARCHAR(20) NULL AFTER endereco,
  ADD COLUMN IF NOT EXISTS complemento VARCHAR(100) NULL AFTER numero,
  ADD COLUMN IF NOT EXISTS bairro VARCHAR(100) NULL AFTER complemento,
  ADD COLUMN IF NOT EXISTS cep VARCHAR(20) NULL AFTER bairro,
  ADD COLUMN IF NOT EXISTS cidade VARCHAR(100) NULL AFTER cep;
