-- Migration: ensure compatibility columns for legacy environments
USE hortifrut;

ALTER TABLE clientes
  ADD COLUMN IF NOT EXISTS cpf_cnpj VARCHAR(50) NULL AFTER nome,
  ADD COLUMN IF NOT EXISTS email VARCHAR(150) NULL AFTER telefone,
  ADD COLUMN IF NOT EXISTS uf VARCHAR(2) NULL AFTER email,
  ADD COLUMN IF NOT EXISTS status TINYINT(1) NOT NULL DEFAULT 1 AFTER uf,
  ADD COLUMN IF NOT EXISTS endereco VARCHAR(255) NULL AFTER nome,
  ADD COLUMN IF NOT EXISTS numero VARCHAR(20) NULL AFTER endereco,
  ADD COLUMN IF NOT EXISTS complemento VARCHAR(100) NULL AFTER numero,
  ADD COLUMN IF NOT EXISTS bairro VARCHAR(100) NULL AFTER complemento,
  ADD COLUMN IF NOT EXISTS cep VARCHAR(20) NULL AFTER bairro;

ALTER TABLE fornecedores
  ADD COLUMN IF NOT EXISTS endereco VARCHAR(255) NULL AFTER razao_social,
  ADD COLUMN IF NOT EXISTS numero VARCHAR(20) NULL AFTER endereco,
  ADD COLUMN IF NOT EXISTS complemento VARCHAR(100) NULL AFTER numero,
  ADD COLUMN IF NOT EXISTS bairro VARCHAR(100) NULL AFTER complemento,
  ADD COLUMN IF NOT EXISTS cep VARCHAR(20) NULL AFTER bairro,
  ADD COLUMN IF NOT EXISTS cidade VARCHAR(100) NULL AFTER cep,
  ADD COLUMN IF NOT EXISTS email VARCHAR(150) NULL AFTER cnpj,
  ADD COLUMN IF NOT EXISTS inscricao_estadual VARCHAR(100) NULL AFTER telefone,
  ADD COLUMN IF NOT EXISTS status TINYINT(1) NOT NULL DEFAULT 1 AFTER inscricao_estadual,
  ADD COLUMN IF NOT EXISTS uf VARCHAR(2) NULL AFTER status;

ALTER TABLE motoristas
  ADD COLUMN IF NOT EXISTS placa VARCHAR(50) NULL AFTER nome,
  ADD COLUMN IF NOT EXISTS veiculo VARCHAR(150) NULL AFTER placa,
  ADD COLUMN IF NOT EXISTS uf VARCHAR(2) NULL AFTER veiculo,
  ADD COLUMN IF NOT EXISTS status TINYINT(1) NOT NULL DEFAULT 1 AFTER uf;

ALTER TABLE compras
  ADD COLUMN IF NOT EXISTS data_envio_prevista DATE NULL AFTER data_compra,
  ADD COLUMN IF NOT EXISTS data_entrega_prevista DATE NULL AFTER data_envio_prevista;

ALTER TABLE vendas
  ADD COLUMN IF NOT EXISTS data_envio_prevista DATE NULL AFTER data_venda,
  ADD COLUMN IF NOT EXISTS data_entrega_prevista DATE NULL AFTER data_envio_prevista;
