ALTER TABLE compras_cabecalho ADD COLUMN IF NOT EXISTS created_by INT NULL REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE vendas_cabecalho ADD COLUMN IF NOT EXISTS created_by INT NULL REFERENCES users(id) ON DELETE SET NULL;
