CREATE TABLE IF NOT EXISTS tenants (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE users ADD COLUMN IF NOT EXISTS tenant_id INT NULL REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE clientes ADD COLUMN IF NOT EXISTS tenant_id INT NULL REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE fornecedores ADD COLUMN IF NOT EXISTS tenant_id INT NULL REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE motoristas ADD COLUMN IF NOT EXISTS tenant_id INT NULL REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE produtos ADD COLUMN IF NOT EXISTS tenant_id INT NULL REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE compras_cabecalho ADD COLUMN IF NOT EXISTS tenant_id INT NULL REFERENCES tenants(id) ON DELETE SET NULL;
ALTER TABLE vendas_cabecalho ADD COLUMN IF NOT EXISTS tenant_id INT NULL REFERENCES tenants(id) ON DELETE SET NULL;
